### ISSUE TITLE
Question regarding the generation of the preprocessing.json file

### ISSUE THREAD

**Issue by bwich** [DIAGNijmegen/picai_prep#28]
Dear @joeranbosma ,

thank you very much for your great work and sharing your code! We would really like to use your package, however, unfortunately, I am struggling to generate the preprocessing.json file which is required to convert my DICOMs to MHA (https://github.com/DIAGNijmegen/picai_prep#dicom-archive--mha-archive). 

We have tried to use the example from the README.md file, but the code returned:

```
lib/python3.10/site-packages/picai_prep/examples/dcm2mha/sample_archive.py", line 130, in generate_dcm2mha_settings
    raise ValueError("Did not find any DICOM series, aborting.")
ValueError: Did not find any DICOM series, aborting.
```

The folder, that I am referencing, of course contains DICOMs acquired at a SIEMENS scanner. We have tried to directly input a file path and providing the path to a folder full of DICOMs. However, none of these options worked. What file structure does the code expect?

Thank you so much!

Best regards
@bwich

**Comment by joeranbosma** [comment]
Hi @bwich,

To convert a single DICOM sequence (a single folder containing the `xyz.dcm` files of a single sequence), you only need to read & write the scan. This can be done as follows:

```python
from picai_eval.dcm2mha import DICOMImageReader
from picai_prep import atomic_image_write

image = DICOMImageReader(path=path_to_dicom_folder).image
atomic_image_write(image, path_to_target_mha_file)
```

The rest of `picai_prep`'s DICOM -> MHA conversion is aimed at:
- Efficiently processing many sequences (using multiprocessing)
- Use DICOM metadata to determine which sequences to convert, and how to name these sequences in the MHA archive.

To use this part of `picai_prep`, you do need the `dcm2mha_settings.json` to specify how the DICOM -> MHA conversion should be done. The default folder structure for the DICOM archive is:

```bash
/path/to/archive/
    ├── [patient UID]/
        ├── [study UID]/
            ├── [series UID]/
                ├── slice-1.dcm
                ...
                ├── slice-n.dcm
```

With this structure, you can [follow the documentation as-is](https://github.com/DIAGNijmegen/picai_prep#dicom-archive--mha-archive). However, if your folder structure is different, you need to generate the `dcm2mha_settings.json` yourself. To do this, I advise to copy the [sample_archive.py](https://github.com/DIAGNijmegen/picai_prep/blob/main/src/picai_prep/examples/dcm2mha/sample_archive.py) script, and adapt this to your folder structure.

In this script you can also specify how to [determine which DICOM sequences to convert](https://github.com/DIAGNijmegen/picai_prep/blob/main/src/picai_prep/examples/dcm2mha/sample_archive.py#L91-L120). For our use case (prostate cancer detection in MRI), we used the DICOM's `SeriesDescription` to look for predefined tags (such as `t2_tse_sag`). The keys of this mappings dictionary become the names in the MHA archive. So a DICOM sequence with `SeriesDescription=t2_tse_sag` will be stored as `[patient_id]_[study_id]_sag.mha`.

Hope this helps,
Joeran

**Comment by joeranbosma** [comment]
Hi @bwich,
Were you able to solve the issue?

**Comment by bwich** [comment]
Thank you so much! I apologize for my late response. Yes, your response helped! Thank you!

**Comment by joeranbosma** [comment]
That's great to hear!
