### ISSUE TITLE
Dataset.json file cannot be found during nnU-Net Raw Data Archive → nnDetection Raw Data Archive conversion.

### ISSUE THREAD

**Issue by Shammasjaved** [DIAGNijmegen/picai_prep#51]
I was converting data from nnU-Net Raw Data Archive → nnDetection Raw Data Archive format but getting error.

Copying annotations from D:\Thesis\thesis_code\output\nnUNet_raw_data\Task2201_picai_baseline\labelsTr to D:\Thesis\thesis_code\output\nndet_raw_data\Task2201_picai_baseline\raw_splitted\labelsTr
Copying scans from D:\Thesis\thesis_code\output\nnUNet_raw_data\Task2201_picai_baseline\imagesTr to D:\Thesis\thesis_code\output\nndet_raw_data\Task2201_picai_baseline\raw_splitted\imagesTr
Traceback (most recent call last):
  File "D:\Thesis\thesis_code\Data_prep3.py", line 3, in <module>
    nnunet2nndet(
  File "C:\Users\Shammas Javed\AppData\Local\Programs\Python\Python310\lib\site-packages\picai_prep\nnunet2nndet.py", line 161, in nnunet2nndet
    nnunet2nndet_dataset_json_conversion(
  File "C:\Users\Shammas Javed\AppData\Local\Programs\Python\Python310\lib\site-packages\picai_prep\nnunet2nndet.py", line 96, in nnunet2nndet_dataset_json_conversion
    with open(path_src) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Thesis\\thesis_code\\output\\nnUNet_raw_data\\Task2201_picai_baseline\\dataset.json'
PS D:\Thesis\thesis_code> 

I think there should be a dataset.json file created during MHA Archive → nnU-Net Raw Data Archive conversion. But no such file is created in my case.  Can you help me to resolve this issue.

**Comment by joeranbosma** [comment]
Hi @Shammasjaved,

You are right, the dataset.json file should be created during the MHA Archive to nnU-Net Raw Data Archive conversion. I checked the documentation, and found that the command to create this file was missing when running the conversion from Python:

```python
from picai_prep import MHA2nnUNetConverter

archive = MHA2nnUNetConverter(
    scans_dir="/input/path/to/mha/archive",
    annotations_dir="/input/path/to/annotations",  # defaults to input_path
    output_dir="/output/path/to/nnUNet_raw_data",
    mha2nnunet_settings="/path/to/mha2nnunet_settings.json",
)
archive.convert()
```

This should have an additional line:

```python
archive.create_dataset_json()
```

When using the command line or Docker container to convert the dataset, the dataset.json file should have been generated already.

Were you indeed using the Python interface? I've now updated the documentation to include the dataset.json generation.

**Comment by Shammasjaved** [comment]
Thanks issue was resolved
